image:
  type: Tiled
  nx_tiles: 10
  ny_tiles: 10
  stamp_size: 33
  pixel_scale: 0.263
  noise:
    type: Gaussian
    sigma: 1
  random_seed: 153

psf:
  type: Gaussian
  fwhm: 0.9
  flux: 1

gal:
  type: Exponential
  half_light_radius: 0.5
  flux: 64000
  shift:
    type: XY
    x: {type: Random, min: -0.263, max: 0.263}
    y: {type: Random, min: -0.263, max: 0.263}
  shear:
    type: G1G2
    g1: 0.02
    g2: 0.0

output:
  file_name: gals.fits
