modules:
  - multi_image_mod

image:
  type: Scattered
  nobjects: 100
  xsize: 2048
  ysize: 4096

psf:
  type: Gaussian
  fwhm: 0.9

gal:
  type: Exponential
  half_light_radius:
    type: Random
    min: 0.5
    max: 1.5
  flux: 1000.0

output:
  type: MultiImageMod
  num_to_do: 16
