modules:
  - matts_misc.piff_wl_sims
  - numpy

input:
    des_piff:
      file_name: /Users/Matt/DESDATA/y3_piff/y3a1-v29/239273/D00239273_i_c21_r2362p01_piff.fits

image:
  type: Tiled
  nx_tiles: 10
  ny_tiles: 10
  stamp_size: 33
  pixel_scale: 0.263
  noise:
    type: Gaussian
    sigma: 1
  random_seed: 153

psf:
  type: DES_Piff
  smooth: False
  flux: 1

  # get random positions on the sky for the PSFs
  image_pos:
    type : XY
    x: {type: Random, min: 1, max: 2048}
    y: {type: Random, min: 1, max: 2048}

stamp:
  draw_method: 'no_pixel'

gal:
  type: Exponential
  half_light_radius: 0.5
  flux: 64000
  shear:
    type: G1G2
    g1: 0.02
    g2: 0.0

output:
  file_name: gals.fits
