#!/usr/bin/env python
import logging
import sys

import click
import yaml

from simple_des_y3_sims_mcal import run_mcal

for lib in ['simple_des_y3_sims_mcal']:
    lgr = logging.getLogger(lib)
    hdr = logging.StreamHandler(sys.stdout)
    hdr.setFormatter(logging.Formatter(logging.BASIC_FORMAT))
    lgr.setLevel(logging.DEBUG)
    lgr.addHandler(hdr)


@click.command()
@click.option('--tilename', type=str, required=True,
              help='the coadd tile to simulate')
@click.option('--bands', type=str, required=True,
              help=('a list of bands to run as '
                    'a concatnated string (e.g., "riz")'))
@click.option('--output-desdata', type=str, required=True,
              help='the output DESDATA directory')
@click.option('--mcal-config-file', type=str, required=True,
              help='the YAML config file for metacal')
@click.option('--seed', type=int, required=True,
              help='the base RNG seed')
def main(tilename, bands, output_desdata, mcal_config_file, seed):
    with open(mcal_config_file, 'r') as fp:
        mcal_config = yaml.load(fp, Loader=yaml.Loader)
    mcal_config['jobs']['bands'] = [b for b in bands]

    run_mcal(tilename, output_desdata, mcal_config, seed)


if __name__ == '__main__':
    main()
